name: CMake

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Debug

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: configure
      run: mkdir build && cd build && cmake -DBUILD_WITH_TESTS=1 -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_FLAGS="-Werror" ..

    - name: make
      run: cd build && make

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: test
      run: cd build && make test
