name: CMake

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main" ]


jobs:

  release_build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: configure
      run: mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_FLAGS="-Werror" ..

    - name: make
      run: cd build && make

  debug_build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: configure
      run: mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_FLAGS="-Werror" ..

    - name: make
      run: cd build && make

  release_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: configure
      run: mkdir build && cd build && cmake -DBUILD_WITH_TESTS=1 -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_FLAGS="-Werror" ..

    - name: make
      run: cd build && make

    - name: test
      run: cd build && make test

  debug_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: configure
      run: mkdir build && cd build && cmake -DBUILD_WITH_TESTS=1 -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_FLAGS="-Werror" ..

    - name: make
      run: cd build && make

    - name: test
      run: cd build && make test
